config/routes.rb
Rails.application.routes.draw do

  root to: 'users#index'

  post '/login', to: "sessions#create"
  get '/logout', to: "sessions#destroy"
  resources :users do

    member do
      get '/edit_measurables', to: "users#edit_measurables"
      patch '/update_measurables', to: "users#update"
    end

    resources :game_stats, only: [:new, :create, :edit, :update]
  end

end

app/models/game_stat.rb
class GameStat < ActiveRecord::Base
	belongs_to :user

  validates :opponent, presence: true
  validates :date, presence: true
  validates :game_stat_year, presence: true
end

app/models/player_position.rb
class PlayerPosition < ActiveRecord::Base
  belongs_to :user
  belongs_to :position
end

app/models/position.rb
class Position < ActiveRecord::Base
  has_many :player_positions
  has_many :users, through: :player_positions
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :player_positions
  has_many :positions, through: :player_positions
  has_many :game_stats

  has_secure_password validations: false
  validates :password, presence: true, on: :create, length: {minimum: 5}

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :username, presence: true, uniqueness: true
  validates :email, presence: true
  validates :city, presence: true
  validates :state, presence: true
  validates :school, presence: true
  validates :graduation_year, presence: true


  def total_stat_category(year, category)
    total = 0
    self.game_stats.each do |game_stat|
      if game_stat.game_stat_year == year
        total += game_stat.read_attribute(category) if !game_stat.read_attribute(category).nil?
      end
    end
    total
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :logged_in?

  def current_user
    @current_user ||= User.find(session[:user_id]) if session[:user_id]
  end

  def logged_in?
    !!current_user
  end

  def require_user
    if !logged_in?
      flash[:error] = "You are not logged in."
      redirect_to root_path
    end
  end

  def same_user
    if @user && current_user != @user
      flash[:error] = "You must be logged into correct account."
      redirect_to root_path
    end
  end
end

app/controllers/game_stats_controller.rb
class GameStatsController < ApplicationController
  before_action :set_game_stat_user
  before_action :set_game_stat, only: [:edit, :update]
  before_action :require_user
  before_action :same_user

  def new
    @game_stat = GameStat.new
  end

  def create
    @game_stat = GameStat.new(game_stat_params)
    @game_stat.user = current_user
   
    if @game_stat.save
      flash[:notice] = "Your statistics have been saved."
      redirect_to user_path(@game_stat.user)
    else
      flash[:error] = "Opponent, date, and year must be filled or selected."
      render :new
    end
  end

  def edit
    
  end

  def update

    if @game_stat.update(game_stat_params)
      flash[:notice] = "Your statistics have been updated."
      redirect_to user_path(current_user)
    else
      flash[:error] = "Opponent, date, and year must be filled or selected."
      render :edit
    end   
  end

  private

  def game_stat_params
    params.require(:game_stat).permit(:game_stat_year, :date, :opponent, :pass_attempts, :pass_completions, :pass_yards, :pass_tds, :pass_int, :rush_attempts, :rush_yards, :rush_tds,
      :receptions, :receiving_yards, :receiving_tds, :fumbles, :fumbles_lost, :tackles, :sacks, :interceptions, :field_goal_attempts, :field_goals_made,
      :pat_attempts, :pat_made)
  end

  def set_game_stat
    @game_stat = GameStat.find(params[:id])
  end

  def set_game_stat_user
    @user = User.find(params[:user_id])
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

  def create
    user = User.new
    user = User.find_by(username: params[:username])

    if user && user.authenticate(params[:password]) 
      session[:user_id] = user.id
      redirect_to user_path(user)
    else
      flash[:error] = "Incorrect username or password."
      redirect_to root_path
    end
  end

  def destroy
    session[:user_id] = nil
    flash[:notice] = "You are now logged out."
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :edit_measurables, :update_measurables]
  before_action :same_user, only: [:edit, :update, :edit_measurables, :update_measurables]
  
  def show
  
  end

  def new
    if current_user
      flash[:error] = "You must be logged out to create another profile."
      redirect_to user_path(current_user)
    else
      @user = User.new
    end
  end

  def create
    @user = User.new(user_params)

    if @user.save
      session[:user_id] = @user.id
      flash[:notice] = "Your profile was created. You are now one step closer to being recruited to play at the next level!"
      redirect_to user_path(@user)
    else
      flash[:error] = "First_name, last_name, username, city, state, school fields, and graduation year cannot be empty. Username must be unique."
      render :new
    end
  end

  def edit
  end

  def update
    if @user.update(user_params)
      flash[:notice] = "Your profile was updated!"
      redirect_to user_path(@user)
    else
      flash[:error] = "First_name, last_name, city, state, school fields, and graduation year cannot be empty." #DRY
      render :edit
    end
  end

  def edit_measurables
    if current_user
      render :edit_measurables
    else
      flash[:error] = "Please log in."
      redirect_to root_path
    end
  end

  private

  def user_params
    params.require(:user).permit(:first_name, :last_name, :password, :age, :height, :weight, :city, :state, :school, :gpa, :username, :email, :graduation_year, 
    :forty, :bench_press, :squat, :vertical, :broad_jump, :shuttle, :three_cone, :SAT, :ACT, position_ids: [])
  end

  def set_user
    @user = User.find(params[:id])
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def convert_inch(inch)
    (inch/12).to_s + '\'' + (inch%12).floor.to_s + "\""
  end

  def us_states
    [
      'AK','AL','AR','AZ','CA','CO','CT','DC','DE','FL',
      'GA','HI','IA','ID','IL','IN','KS','KY','LA','MA',
      'MD','ME','MI','MN','MO','MS','MT','NC','ND','NE',
      'NH','NJ','NM','NV','NY','OH','OK','OR','PA','RI',
      'SC','SD','TN','TX','UT','VA','VT','WA','WI','WV','WY'
    ]
  end
end

app/helpers/users_helper.rb
module UsersHelper

  def gravatar_for(user)
    gravatar_id = Digest::MD5::hexdigest(user.email.downcase)
    gravatar_url = "https://secure.gravatar.com/avatar/#{gravatar_id}"
    image_tag(gravatar_url, alt: user.username, class: "gravatar")
  end

  def same_profile?
    current_user.id == params[:id].to_i
  end
end

app/views/game_stats/_form.html.erb
<div class= 'well'>
  <%= form_for [@user, @game_stat] do |f| %>
    <div class='control-group'>
      <%= f.label :game_stat_year, 'Year' %>
      <%= f.select :game_stat_year, options_for_select(["Freshman", "Sophomore", "Junior", "Senior"]) %>
    </div>
    <div class='control-group'>
      <%= f.label :date %>
      <%= f.date_field :date %>
    </div>
    <div class='control-group>'>
      <%= f.label :opponent %>
      <%= f.text_field :opponent %>
    </div>
    <div class='control-group>'>
      <%= f.label :pass_attempts, 'Pass Att' %>
      <%= f.number_field :pass_attempts %>
    </div>
    <div class='control-group>'>
      <%= f.label :pass_completions, 'Pass Comp' %>
      <%= f.number_field :pass_completions %>
    </div>
    <div class='control-group>'>
      <%= f.label :pass_yards, 'Pass Yds' %>
      <%= f.number_field :pass_yards %>
    </div>
    <div class='control-group>'>
      <%= f.label :pass_tds, 'Pass TD' %>
      <%= f.number_field :pass_tds %>
    </div>
    <div class='control-group>'>
      <%= f.label :pass_int, 'Pass Int' %>
      <%= f.number_field :pass_int %>
    </div>
    <div class='control-group>'>
      <%= f.label :rush_attempts, 'Rush Att' %>
      <%= f.number_field :rush_attempts %>
    </div>
    <div class='control-group>'>
      <%= f.label :rush_yards, 'Rush Yds' %>
      <%= f.number_field :rush_yards %>
    </div>
    <div class='control-group>'>
      <%= f.label :rush_tds, 'Rush TD' %>
      <%= f.number_field :rush_tds %>
    </div>
    <div class='control-group>'>
      <%= f.label :receptions, 'Rec' %>
      <%= f.number_field :receptions %>
    </div>
    <div class='control-group>'>
      <%= f.label :receiving_yards, 'Rec Yds' %>
      <%= f.number_field :receiving_yards %>
    </div>
    <div class='control-group>'>
      <%= f.label :receiving_tds, 'Rec TD' %>
      <%= f.number_field :receiving_tds %>
    </div>
    <div class='control-group>'>
      <%= f.label :fumbles %>
      <%= f.number_field :fumbles %>
    </div>
    <div class='control-group>'>
      <%= f.label :fumbles_lost, 'Fumbles Lost' %>
      <%= f.number_field :fumbles_lost %>
    </div>
    <div class='control-group>'>
      <%= f.label :tackles %>
      <%= f.number_field :tackles %>
    </div>
    <div class='control-group>'>
      <%= f.label :sacks %>
      <%= f.number_field :sacks %>
    </div>
    <div class='control-group>'>
      <%= f.label :interceptions, 'Int' %>
      <%= f.number_field :interceptions %>
    </div>
    <div class='control-group>'>
      <%= f.label :field_goal_attempts, 'FGA Att' %>
      <%= f.number_field :field_goal_attempts %>
    </div>
    <div class='control-group>'>
      <%= f.label :field_goals_made, 'FGA Made' %>
      <%= f.number_field :field_goals_made %>
    </div>
    <div class='control-group>'>
      <%= f.label :pat_attempts, 'PAT Att' %>
      <%= f.number_field :pat_attempts %>
    </div>
    <div class='control-group>'>
      <%= f.label :pat_made, 'PAT Made' %>
      <%= f.number_field :pat_made %>
    </div>
    <%= f.submit (@game_stat.new_record? ? 'Submit Stats' : 'Update Stats') , class: 'btn btn-success' %>
  <% end %>
</div>

app/views/game_stats/edit.html.erb
<div>
  <h1>Edit Game Statistics</h1>
</div>
<%= render 'form' %>

app/views/game_stats/new.html.erb
<div>
  <h1>Game Statistics</h1>
</div>
<%= render 'form' %>

app/views/layouts/_messages.html.erb
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name == :notice ? "success" : "error" %>">
      <a class="close" data-dismiss="alert">&#215;</a>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
  <span class="sr-only">Toggle navigation</span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
  <span class="icon-bar"></span>
</button>
<!--<a class="navbar-brand" href="#">Recruit Me</a>-->
 <%= link_to "Recruit Me", root_path, :class => 'navbar-brand'%>
</div>
<div id="navbar" class="navbar-collapse collapse">
  <!--<form class="navbar-form navbar-right">-->
  <% if !logged_in? %>
    <%= form_tag '/login', class: 'navbar-form navbar-right' do %>
      <div class="form-group">
        <!--<input type="text" placeholder="Email" class="form-control">-->
        <%= text_field_tag :username, nil, placeholder: "Username" %>
      </div>
      <div class="form-group">
        <!--<input type="password" placeholder="Password" class="form-control">-->
        <%= password_field_tag :password, nil, placeholder: "Password" %>
      </div>
      <!--<button type="submit" class="btn btn-success">Log in</button>-->
      <div class='form-group'>
        <%= submit_tag 'Login', class: 'btn btn-success' %>
      </div>
    <% end %>
  <% else %>
    <div class='navbar-form navbar-right'>
      
      <div class="btn-group nav_item">
        <%= link_to('', class: 'btn btn-success dropdown-toggle', 'data-toggle' => 'dropdown') do %>
        <%= current_user.username %>
        <span class='caret'></span>
      <% end %>
      <ul class='dropdown-menu'>
        <li><%= link_to "Edit Profile", edit_user_path(current_user) %></li>
        <li><%= link_to "Edit Measurables", edit_measurables_user_path(current_user) %></li>
        <li><%= link_to "View Profile", user_path(current_user)  %></li>
        <li><%= link_to "Logout", logout_path %></li>
      </ul>
      </div>
    </div>
  <% end %>
  <!--</form>-->
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
	<meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Recruit Me</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
  <header>
    <div class='navbar'>
      <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
          <div class="navbar-header">
            <%= render 'layouts/navigation' %>
          </div><!--/.navbar-collapse -->
        </div>
      </nav>
    </div>
  </header>
  <div>
   <%= render 'layouts/messages' %>
   <%= yield %>
 </div>
</body>
</html>

app/views/users/_form.html.erb
<div class= 'well'>
  <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :first_name, 'First Name' %>
      <%= f.text_field :first_name %>
    </div>
    <div class='control-group>'>
      <%= f.label :last_name, 'Last Name' %>
      <%= f.text_field :last_name %>
    </div>
    <div class='control-group>'>
      <%= f.label :username %>
      <%= f.text_field :username %>
    </div>
    <div class='control-group>'>
      <%= f.label :password %>
      <%= f.password_field :password %>
    </div>
    <div class='control-group>'>
      <%= f.label :email %>
      <%= f.text_field :email %>
    </div>
    <div class='control-group>'>
      <%= f.label :age %>
      <%= f.number_field :age %>
    </div>
    <div class='control-group>'>
      <%= f.label :height %>
      <%= f.select :height, options_for_select((48..96).to_a.map { |inch| convert_inch(inch) })%>
    </div>
    <div class='control-group>'>
      <%= f.label :weight %>
      <%= f.number_field :weight %>
    </div>
    <div class='control-group>'>
      <%= f.label :city %>
      <%= f.text_field :city %>
    </div>
    <div class='control-group>'>
      <%= f.label :state %>
      <%= f.select :state, options_for_select(us_states) %>
    </div>
    <div class='control-group>'>
      <%= f.label :school %>
      <%= f.text_field :school %>
    </div>
    <div class='control-group'>
      <%= f.label :graduation_year, 'Graduation Year' %>
      <%= f.number_field :graduation_year %>
    </div>
    <div class='control-group>'>
      <%= f.label :gpa, 'GPA' %>
      <%= f.number_field :gpa, step: 'any' %>
    </div>
    <div class='control-group>'>
      <%= f.label :position, 'Position(s)' %>
      <%= f.collection_select(:position_ids, Position.all, :id, :position_title, {}, {:multiple => true}) %>
    </div>
    <%= f.submit (@user.new_record? ? 'Register' : 'Update Profile') , class: 'btn btn-success' %>
  <% end %>
</div>

app/views/users/_user_game_stats.html.erb
<table id="user_game_stat_table">

  <thead>
    <tr>
      <% if logged_in? %>
        <td></td>
      <% end %>
      <td>Year</td>
      <td>Date</td>
      <td>Opponent</td>
      <td>Pass Att</td>
      <td>Pass Comp</td>
      <td>Pass Yds</td>
      <td>Pass TD</td>
      <td>Pass Int</td>
      <td>Rush Att</td>
      <td>Rush Yds</td>
      <td>Rush TD</td>
      <td>Rec</td>
      <td>Rec Yds</td>
      <td>Rec TD</td>
      <td>Fumbles</td>
      <td>Fumbles Lost</td>
      <td>Tackles</td>
      <td>Sacks</td>
      <td>Int</td>
      <td>FGA</td>
      <td>FGM</td>
      <td>PAT Att</td>
      <td>PAT Made</td>
    </tr>
  </thead>

  <tbody>
    <% if !@user.game_stats.nil? %>
      <% @user.game_stats.each do |game_stat| %>
        <% if game_stat.game_stat_year == year %>
          <tr>
            <% if logged_in? && same_profile? %>
              <td><%= link_to "Edit", edit_user_game_stat_path(@user, game_stat) %></td>
            <% end %>
            <td><%= game_stat.game_stat_year unless game_stat.game_stat_year.nil? %></td>
            <td><%= game_stat.date unless game_stat.date.nil? %></td>
            <td><%= game_stat.opponent unless game_stat.opponent.nil? %></td>
            <td><%= game_stat.pass_attempts unless game_stat.pass_attempts.nil? %></td>
            <td><%= game_stat.pass_completions unless game_stat.pass_completions.nil? %></td>
            <td><%= game_stat.pass_yards unless game_stat.pass_yards.nil? %></td>
            <td><%= game_stat.pass_tds unless game_stat.pass_tds.nil? %></td>
            <td><%= game_stat.pass_int unless game_stat.pass_int.nil? %></td>
            <td><%= game_stat.rush_attempts unless game_stat.rush_attempts.nil? %></td>
            <td><%= game_stat.rush_yards unless game_stat.rush_yards.nil? %></td>
            <td><%= game_stat.rush_tds unless game_stat.rush_tds.nil? %></td>
            <td><%= game_stat.receptions unless game_stat.receptions.nil? %></td>
            <td><%= game_stat.receiving_yards unless game_stat.receiving_yards.nil? %></td>
            <td><%= game_stat.receiving_tds unless game_stat.receiving_tds.nil? %></td>
            <td><%= game_stat.fumbles unless game_stat.fumbles.nil? %></td>
            <td><%= game_stat.fumbles_lost unless game_stat.fumbles_lost.nil? %></td>
            <td><%= game_stat.tackles unless game_stat.tackles.nil? %> </td>
            <td><%= game_stat.sacks unless game_stat.sacks.nil? %> </td>
            <td><%= game_stat.interceptions unless game_stat.interceptions.nil? %></td>
            <td><%= game_stat.field_goal_attempts unless game_stat.field_goal_attempts.nil? %></td>
            <td><%= game_stat.field_goals_made unless game_stat.field_goals_made.nil? %></td>
            <td><%= game_stat.pat_attempts unless game_stat.pat_attempts.nil? %></td>
            <td><%= game_stat.pat_made unless game_stat.pat_made.nil? %></td>
          </tr>

        <% end %>
      <% end %>
    <% end %>
  
    <tr>
      <td></td>
      <td></td>
      <% if logged_in? %>
        <td></td>
      <% end %>
      <td>Total</td>
      <td><%= @user.total_stat_category(year, "pass_attempts") %></td>
      <td><%= @user.total_stat_category(year, "pass_completions") %></td>
      <td><%= @user.total_stat_category(year, "pass_yards") %></td>
      <td><%= @user.total_stat_category(year, "pass_tds") %></td>
      <td><%= @user.total_stat_category(year, "pass_int") %></td>
      <td><%= @user.total_stat_category(year, "rush_attempts") %></td>
      <td><%= @user.total_stat_category(year, "rush_yards") %></td>
      <td><%= @user.total_stat_category(year, "rush_tds") %></td>
      <td><%= @user.total_stat_category(year, "receptions") %></td>
      <td><%= @user.total_stat_category(year, "receiving_yards") %></td>
      <td><%= @user.total_stat_category(year, "receiving_tds") %></td>
      <td><%= @user.total_stat_category(year, "fumbles") %></td>
      <td><%= @user.total_stat_category(year, "fumbles_lost") %></td>
      <td><%= @user.total_stat_category(year, "tackles") %></td>
      <td><%= @user.total_stat_category(year, "sacks") %></td>
      <td><%= @user.total_stat_category(year, "interceptions") %></td>
      <td><%= @user.total_stat_category(year, "field_goal_attempts") %></td>
      <td><%= @user.total_stat_category(year, "field_goals_made") %></td>
      <td><%= @user.total_stat_category(year, "pat_attempts") %></td>
      <td><%= @user.total_stat_category(year, "pat_made") %></td>
    </tr> 
  </tbody>
</table>

app/views/users/edit.html.erb
<div>
  <h1> Edit Your Profile </h1>
</div>
<%= render 'form' %>

app/views/users/edit_measurables.html.erb
<div>
  <h1>Edit Measurables</h1>
</div>
<div class= 'well'>
  <%= form_for @user do |f| %>
    <div class='control-group'>
      <%= f.label :forty, '40' %>
      <%= f.number_field :forty, step: 0.01 %> s
    </div>
    <div class='control-group'>
      <%= f.label :bench_press, 'Bench Press' %>
      <%= f.number_field :bench_press %> lbs.
    </div>
    <div class='control-group'>
      <%= f.label :squat %>
      <%= f.number_field :squat %> lbs.
    </div>
    <div class='control-group'>
      <%= f.label :vertical %>
      <%= f.number_field :vertical %> in.
    </div>
    <div class='control-group'>
      <%= f.label :broad_jump, 'Broad Jump' %>
      <%= f.number_field :broad_jump %> in.
    </div>
    <div class='control-group'>
      <%= f.label :shuttle %>
      <%= f.number_field :shuttle, step: 0.01 %> s
    </div>
    <div class='control-group'>
      <%= f.label :three_cone, 'Three Cone' %> 
      <%= f.number_field :three_cone, step: 0.01 %> s
    </div>
    <div class='control-group'>
      <%= f.label :SAT, 'SAT' %>
      <%= f.number_field :SAT %>
    </div>
    <div class='control-group'>
      <%= f.label :ACT, 'ACT' %>
      <%= f.number_field :ACT %>
    </div>
    <%= f.submit 'Update Measurables' , class: 'btn btn-success' %>
  <% end %>
</div>

app/views/users/index.html.erb
    <!-- Main jumbotron for a primary marketing message or call to action -->
    <div class="jumbotron">
      <div class="container">
        <h1>The next level of football awaits you!</h1>
        <p>This is a web application that combines some features of rivals.com and facebook. This site is designed to give high school football players a way to customize a profile and compile their stats and highlights. These high school student-athletes can then send these profiles to college football programs of their interest in hopes of increasing their chances of receiving an offer to play college football for one of those programs!</p>
        <p>
          To see an example profile, use username - "trojan62" and password - "password".
        </p>
        <% if !logged_in? %>
          <p><!--<a class="btn btn-primary btn-lg" href="#" role="button">Learn more &raquo;</a>-->
            <%= link_to 'Register', new_user_path, class: 'btn btn-primary btn-lrg' %>
          </p>
        <% end %>
      </div>
    </div>

    

      <hr>

      <footer>
        <p>&copy; Company 2014</p>
      </footer>
    </div> <!-- /container -->

app/views/users/new.html.erb
<div>
  <h1>Register</h1>
</div>
<%= render 'form' %>

app/views/users/show.html.erb
<div>
  <h3><%= @user.first_name %> <%= @user.last_name %>'s Profile</h3>
</div>

<div class="row">
  <aside class="col-md-4">
    <h1> <%= gravatar_for(@user) %> </h1>
  </aside>
</div>

<div class='well'>
  <dl class='dl-horizontal'>
    <dt>Username:</dt>
    <dd><%= @user.username %></dd>
    <dt>Name:</dt>
    <dd><%= @user.first_name %> <%= @user.last_name %><dd>
    <dt>Email:</dt>
    <dd><%= @user.email %></dd>
    <dt>Age:</dt>
    <dd><%= @user.age %></dd>  
    <dt>Height:</dt>
    <dd><%= @user.height %></dd>
    <dt>Weight:</dt>
    <dd><%= @user.weight %> <%= 'lbs.' if @user.weight %></dd>
    <dt>State:</dt>
    <dd><%= @user.state %></dd> 
    <dt>City:</dt>
    <dd><%= @user.city %></dd>
    <dt>School:</dt>
    <dd><%= @user.school %></dd>
    <dt>Graduation year:</dt>
    <dd><%= @user.graduation_year %></dd>
    <dt>GPA:</dt>
    <dd><%= @user.gpa %></dd> 
    <dt>Position(s):</dt>
    <dd>
      <% @user.positions.each do |p|%>
      <%= p.position_title %>
      <% end %>
    </dd>         
  </dl>

  
  <dl class='dl-horizontal'>
    <dt><h4 class='dl-horizontal'> Measurables</h4></dt>
    <dd></dd>
    <dt>40:</dt>
    <dd><%= @user.forty %> <%= 's' if @user.forty %></dd>
    <dt>Bench Press:</dt>
    <dd><%= @user.bench_press %> <%= 'lbs.' if @user.bench_press %></dd>
    <dt>Squat:</dt>
    <dd><%= @user.squat %> <%= 'lbs.' if @user.squat %></dd>
    <dt>Vertical:</dt>
    <dd><%= @user.vertical %> <%= 'in.' if @user.vertical %></dd>  
    <dt>Broad Jump:</dt>
    <dd><%= @user.broad_jump %> <%= 'in.' if @user.broad_jump %></dd>  
    <dt>Shuttle:</dt>
    <dd><%= @user.shuttle %> <%= 's' if @user.shuttle %></dd>
    <dt>Three Cone:</dt>
    <dd><%= @user.three_cone %> <%= 's' if @user.three_cone %></dd>
    <dt>SAT:</dt>
    <dd><%= @user.SAT %></dd>
    <dt>ACT:</dt>
    <dd><%= @user.ACT %></dd>
  </dl>
</div>

<div class='well' id='stats'>
  <h5><%= @user.username %>'s Statistics <%= link_to "Add Game Statistics", new_user_game_stat_path(@user) if logged_in? && same_profile? %> </h5>

  <ul class='nav nav-tabs'>
    <li class='<%= 'active' if params[:tab].nil? %>'>
      <%= link_to "Freshman Stats", user_path(@user) %>
    </li>
    <li class='<%= 'active' if params[:tab] == 'sophomore' %>'>
      <%= link_to "Sophomore Stats", user_path(@user, tab: 'sophomore') %>
    </li>
    <li class='<%= 'active' if params[:tab] == 'junior' %>'>
      <%= link_to "Junior Stats", user_path(@user, tab: 'junior') %>
    </li>
    <li class='<%= 'active' if params[:tab] == 'senior' %>'>
      <%= link_to "Senior Stats", user_path(@user, tab: 'senior') %>
    </li>
  </ul>

  <% if params[:tab].nil? %>
    <p></p>
    <%= render 'user_game_stats', year: "Freshman" %>
  <% elsif params[:tab] == 'sophomore' %>
    <p></p>
    <%= render 'user_game_stats', year: "Sophomore" %>
  <% elsif params[:tab] == 'junior' %>
    <p></p>
    <%= render 'user_game_stats', year: "Junior" %>
  <% elsif params[:tab] == 'senior' %>
    <p></p>
    <%= render 'user_game_stats', year: "Senior" %>
  <% end %>
</div>